apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    k8s-app: proxy-cloud
    tinykube: proxycloud
  name: proxy-cloud-cert
  namespace: cls-p1xm483u
data:
  cloud.crt: |
    -----BEGIN CERTIFICATE-----
    MIIC8TCCAdmgAwIBAgIIbJxy7tiuvaswDQYJKoZIhvcNAQELBQAwFTETMBEGA1UE
    AxMKa3ViZXJuZXRlczAeFw0yMDAzMjAwOTQ1NDZaFw0yMTAzMjcwODE5NDRaMBAx
    DjAMBgNVBAMTBXByb3h5MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
    rZnjnaIYyFj+LR/Hae5FUA5WDCimFEHVdhbqryXSITnJFdjfV1DOBJpZlMRN7SWS
    miAaMz0r7DLzYNJhyqbAonCXS1EfJNycL/Furk2PIiE7i1QgMZ8nTC8fYnp/ACwG
    yG4cmy9+ffcKx3UL63kfvcI7/f0vnvrUaTXBeQvE5P8VcS53CuHna17lJez6ttQf
    ZmE6o/Sdpnx8yNwHMucEcylVr8yrq+9viLM0F+5ZKaxBel/a2RSXJHIZhufKzsdW
    vRn3sJS0cT3KukXWaTQOM8KFNE7o6Ly2trtIGRYg36LqD1nrkGc1Bp7hecWYuyFX
    NYO0IbxyuSxmmNjRSN+FswIDAQABo0owSDAOBgNVHQ8BAf8EBAMCBaAwEwYDVR0l
    BAwwCgYIKwYBBQUHAwEwIQYDVR0RBBowGIIWd3d3LnByb3h5LnRpbnlrdWJlLmNv
    bTANBgkqhkiG9w0BAQsFAAOCAQEAUm96uiukhhqQBQkqchPar9bBpYrAsq5q/TQO
    Iuk0W9AjiJNhRNJ7HKX+ZEpcSAp0bTf+hzF/lvpPbdxLZVZ8Sy5C0griD+mafeA8
    VJ8Tm9KyZt23XlS+FM22y3lCaSDBuk7XHBrga6QoMS2CTrapYhdKG8OVnxy6/BTM
    J+wOc0F16Oqf8o0ZStP68MujnJJ413dNsWgP/AohDfRtU1x8OLejK1eIhD+7bbZb
    DxNjXHujvNOReqSdoEcs+Li7+m/gWsnkmjKGSefK/j5EPVQsfDMFwhiD0/FoXM+M
    xnJ0/UyWeDZUFVUpDXASvkj9b6SznTW6Tck1FEXLp8oC08ncBg==
    -----END CERTIFICATE-----
  cloud.key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEowIBAAKCAQEArZnjnaIYyFj+LR/Hae5FUA5WDCimFEHVdhbqryXSITnJFdjf
    V1DOBJpZlMRN7SWSmiAaMz0r7DLzYNJhyqbAonCXS1EfJNycL/Furk2PIiE7i1Qg
    MZ8nTC8fYnp/ACwGyG4cmy9+ffcKx3UL63kfvcI7/f0vnvrUaTXBeQvE5P8VcS53
    CuHna17lJez6ttQfZmE6o/Sdpnx8yNwHMucEcylVr8yrq+9viLM0F+5ZKaxBel/a
    2RSXJHIZhufKzsdWvRn3sJS0cT3KukXWaTQOM8KFNE7o6Ly2trtIGRYg36LqD1nr
    kGc1Bp7hecWYuyFXNYO0IbxyuSxmmNjRSN+FswIDAQABAoIBADyya5T30fZqtyQL
    0mtFNdLR0GAb7kVy5zGMva1Tae7YB2iuFRiwVffiB6QuJpjd5C4jP0XfA3ZoMhQO
    OsbiGsQw3ZUl3d/DipBwt6QV1g+20tzaIw92eAT5DN4fujvTKOP3K+VOa8mbEJfA
    YtSH2wM74EHjvjy1soK+mtC5vrPZsLisOVQRlb6kB0spdDYyS9lIwJR5L7LeZorX
    tSJa75sH8EI9qCKAM58AEDYMq1wX0h4igYug2AgoimV8hRn8npSAhCW9dN5jXEsW
    7puMA8yj0jH7k8zKRoKXpk9C5hlzNlfYFWM953uVtG1mN5khIKC4G85RAiEVV22+
    1ro4pCECgYEA0jdpGJ6EmkoDLLbBL2OpfPhM7zcCyWGfZnzOSO283osLt2EVlUdV
    thm/7WUx5aRGhnVI88z/trF7azQe6U0vloRy1Tup1DOBkADFGCPVNuHpKas2act1
    ikXo/Cx2h6MwF6P6bMgORoK4j4TId1BKvrbL5pAPYG1ncIxXas8fDfsCgYEA02j/
    G1eS7hMa5mfg4WH5p6+E9OqoLhfLN9gx8QN+XVf0YOcsDmoMe+IpYXzmCnL47ud0
    K/S0duICSzm/qx0/Qrj28Qzi5GYhpKHTk8+s63eSF4V0wlKAZ8zVgQyVtQdX8aUm
    oyT+yUXWAjKKW8QS4jYAQpT/DFQ4sxILPNvC8akCgYBk0JoganVhoTkgiozfc0Zn
    XpVW6+T0O1M8zYIIy6sWd0ypJ3A4ZTuf132KFkv1u/DurvTLp3bDYR61bQueC5xU
    7TQ9Ox3ZXNI4A4aCazzn0zQE/c1cs2ytYZW4yoIVzpdT3xpMbS0bd7mXarDRN7qA
    +B2Vd2VIc292NHgAC1DzXQKBgQC8e/omKHfpJsNu9OJ8T1vEcyp5KdVz8ubODUTJ
    erHpCwfodXLEDyy+Lq9yKWb3nfXvGhBrOCrFa09cPkpyhwrls/8GftSziZMpMtZu
    DFRBQ0PPEL8+mUu+P9OC0POQiNGRsgq2nb9DN65MGz9b/X5QjJDCzBBwr441qTq3
    sb8msQKBgAmwlUBLnQsWhh2F6ibLMvE+jqfYPe3aVHiL/UHQV4LYiBXOw9HFDB2v
    kFw1kHOkD9JWvfJZtBARUpsPKl5ijYVMMA+nLStRQM5o0SGGFmbpvcILfRB2JBd9
    6dPJW6ZUr568mLV1oNZ/lTMp6iVoIPIIy8Wcll7Y5VLn0oQt+dbz
    -----END RSA PRIVATE KEY-----
  kubelet.crt: |
    -----BEGIN CERTIFICATE-----
    MIIC8TCCAdmgAwIBAgIIbJxy7tiuvaswDQYJKoZIhvcNAQELBQAwFTETMBEGA1UE
    AxMKa3ViZXJuZXRlczAeFw0yMDAzMjAwOTQ1NDZaFw0yMTAzMjcwODE5NDRaMBAx
    DjAMBgNVBAMTBXByb3h5MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
    rZnjnaIYyFj+LR/Hae5FUA5WDCimFEHVdhbqryXSITnJFdjfV1DOBJpZlMRN7SWS
    miAaMz0r7DLzYNJhyqbAonCXS1EfJNycL/Furk2PIiE7i1QgMZ8nTC8fYnp/ACwG
    yG4cmy9+ffcKx3UL63kfvcI7/f0vnvrUaTXBeQvE5P8VcS53CuHna17lJez6ttQf
    ZmE6o/Sdpnx8yNwHMucEcylVr8yrq+9viLM0F+5ZKaxBel/a2RSXJHIZhufKzsdW
    vRn3sJS0cT3KukXWaTQOM8KFNE7o6Ly2trtIGRYg36LqD1nrkGc1Bp7hecWYuyFX
    NYO0IbxyuSxmmNjRSN+FswIDAQABo0owSDAOBgNVHQ8BAf8EBAMCBaAwEwYDVR0l
    BAwwCgYIKwYBBQUHAwEwIQYDVR0RBBowGIIWd3d3LnByb3h5LnRpbnlrdWJlLmNv
    bTANBgkqhkiG9w0BAQsFAAOCAQEAUm96uiukhhqQBQkqchPar9bBpYrAsq5q/TQO
    Iuk0W9AjiJNhRNJ7HKX+ZEpcSAp0bTf+hzF/lvpPbdxLZVZ8Sy5C0griD+mafeA8
    VJ8Tm9KyZt23XlS+FM22y3lCaSDBuk7XHBrga6QoMS2CTrapYhdKG8OVnxy6/BTM
    J+wOc0F16Oqf8o0ZStP68MujnJJ413dNsWgP/AohDfRtU1x8OLejK1eIhD+7bbZb
    DxNjXHujvNOReqSdoEcs+Li7+m/gWsnkmjKGSefK/j5EPVQsfDMFwhiD0/FoXM+M
    xnJ0/UyWeDZUFVUpDXASvkj9b6SznTW6Tck1FEXLp8oC08ncBg==
    -----END CERTIFICATE-----
  kubelet.key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEowIBAAKCAQEArZnjnaIYyFj+LR/Hae5FUA5WDCimFEHVdhbqryXSITnJFdjf
    V1DOBJpZlMRN7SWSmiAaMz0r7DLzYNJhyqbAonCXS1EfJNycL/Furk2PIiE7i1Qg
    MZ8nTC8fYnp/ACwGyG4cmy9+ffcKx3UL63kfvcI7/f0vnvrUaTXBeQvE5P8VcS53
    CuHna17lJez6ttQfZmE6o/Sdpnx8yNwHMucEcylVr8yrq+9viLM0F+5ZKaxBel/a
    2RSXJHIZhufKzsdWvRn3sJS0cT3KukXWaTQOM8KFNE7o6Ly2trtIGRYg36LqD1nr
    kGc1Bp7hecWYuyFXNYO0IbxyuSxmmNjRSN+FswIDAQABAoIBADyya5T30fZqtyQL
    0mtFNdLR0GAb7kVy5zGMva1Tae7YB2iuFRiwVffiB6QuJpjd5C4jP0XfA3ZoMhQO
    OsbiGsQw3ZUl3d/DipBwt6QV1g+20tzaIw92eAT5DN4fujvTKOP3K+VOa8mbEJfA
    YtSH2wM74EHjvjy1soK+mtC5vrPZsLisOVQRlb6kB0spdDYyS9lIwJR5L7LeZorX
    tSJa75sH8EI9qCKAM58AEDYMq1wX0h4igYug2AgoimV8hRn8npSAhCW9dN5jXEsW
    7puMA8yj0jH7k8zKRoKXpk9C5hlzNlfYFWM953uVtG1mN5khIKC4G85RAiEVV22+
    1ro4pCECgYEA0jdpGJ6EmkoDLLbBL2OpfPhM7zcCyWGfZnzOSO283osLt2EVlUdV
    thm/7WUx5aRGhnVI88z/trF7azQe6U0vloRy1Tup1DOBkADFGCPVNuHpKas2act1
    ikXo/Cx2h6MwF6P6bMgORoK4j4TId1BKvrbL5pAPYG1ncIxXas8fDfsCgYEA02j/
    G1eS7hMa5mfg4WH5p6+E9OqoLhfLN9gx8QN+XVf0YOcsDmoMe+IpYXzmCnL47ud0
    K/S0duICSzm/qx0/Qrj28Qzi5GYhpKHTk8+s63eSF4V0wlKAZ8zVgQyVtQdX8aUm
    oyT+yUXWAjKKW8QS4jYAQpT/DFQ4sxILPNvC8akCgYBk0JoganVhoTkgiozfc0Zn
    XpVW6+T0O1M8zYIIy6sWd0ypJ3A4ZTuf132KFkv1u/DurvTLp3bDYR61bQueC5xU
    7TQ9Ox3ZXNI4A4aCazzn0zQE/c1cs2ytYZW4yoIVzpdT3xpMbS0bd7mXarDRN7qA
    +B2Vd2VIc292NHgAC1DzXQKBgQC8e/omKHfpJsNu9OJ8T1vEcyp5KdVz8ubODUTJ
    erHpCwfodXLEDyy+Lq9yKWb3nfXvGhBrOCrFa09cPkpyhwrls/8GftSziZMpMtZu
    DFRBQ0PPEL8+mUu+P9OC0POQiNGRsgq2nb9DN65MGz9b/X5QjJDCzBBwr441qTq3
    sb8msQKBgAmwlUBLnQsWhh2F6ibLMvE+jqfYPe3aVHiL/UHQV4LYiBXOw9HFDB2v
    kFw1kHOkD9JWvfJZtBARUpsPKl5ijYVMMA+nLStRQM5o0SGGFmbpvcILfRB2JBd9
    6dPJW6ZUr568mLV1oNZ/lTMp6iVoIPIIy8Wcll7Y5VLn0oQt+dbz
    -----END RSA PRIVATE KEY-----