apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-edge-cert
  namespace: default
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIICyDCCAbCgAwIBAgIBADANBgkqhkiG9w0BAQsFADAVMRMwEQYDVQQDEwprdWJl
    cm5ldGVzMB4XDTIwMDMyMDA5NDU0NloXDTMwMDMxODA5NDU0NlowFTETMBEGA1UE
    AxMKa3ViZXJuZXRlczCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALyI
    Au1u3oliPeLITC6Iua+laJi1iNmi7efXPLx0QSeH8QL/qEF1s8OUmjnYohJSavVL
    pSySqB614BfxMBPF6w06mInXpAupk9G9vTdEe+TELA8pMDBff0e5i6LyqwLt8ppe
    jcNSzMdHfWlAHvyAa6SnzzTM0YvLI3pXQk7xqP7Td9+8cD5RG10Psa7ZuSjdSObB
    DPuLFx6pMzY9WP7BiwxdRIRcB1AGAZlSsqLDJKQdJnQLrMWd8PKgs8dUjUZ/5Qcp
    1YnpfeqxOMxwbjWCyPs4+bDMjvGsi/Kqhyy94g/HSt/PnfxwiNrUHlcQ6SUWK0Sh
    qVUujIyjH0/ma2eRPMMCAwEAAaMjMCEwDgYDVR0PAQH/BAQDAgKUMA8GA1UdEwEB
    /wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBAIG79fE4bLpFJseomojk/w20eryB
    HBBa5d3BLXrNheSA5mHUE0bdwKrwbyFJJu81owK8hbb7cCREzd+noxfpFB4edf42
    Uqi3r/8djgbDXitpr3CoRZUjNDr/T/fQXsh8EUxGU/Ez3zoxw7F7t8dU+PHQC8RT
    i/KOoSYRiW9txotlxUNEOtf22i/4xzy9Cq3TJayZBRek1u1WTr1xfXjjbVsu9xpM
    IY90mob3Fb5j/Q8MeYZlmGvydGNIwIVFCZb5d1DtiDMgYm6I5CfMKngN6AmxOArf
    ocV7bTbOPFvZgPV9Dj1LSsMMDy0NGed2+/zvRWUS1rB3s5xL+wpDyUGh0SY=
    -----END CERTIFICATE-----
  kubelet-client.crt: |
    -----BEGIN CERTIFICATE-----
    MIIC5zCCAc+gAwIBAgIIONirWMPnfwQwDQYJKoZIhvcNAQELBQAwFTETMBEGA1UE
    AxMKa3ViZXJuZXRlczAeFw0yMDAzMjAwOTQ1NDZaFw0yMTAzMjcwODUzNTlaMCkx
    FzAVBgNVBAoTDnN5c3RlbTptYXN0ZXJzMQ4wDAYDVQQDEwVwcm94eTCCASIwDQYJ
    KoZIhvcNAQEBBQADggEPADCCAQoCggEBALqsp6gMpD+7gFzJfURrqyEMyxJTMbrp
    iYH9EMyYQVnZgJGKogYoLyYO+VGthhwq/h1zM0WoO9Lg4gjWDAOCE8uGeX+eI3du
    P6YpBkUx+y5jVGgmpx++872Vx1doSdtdQgg6IgwmQzqSwhUFym81YIvXuRvDhD/k
    V4wUC/qLtdWbI0SRBsi0lljwIPj/I+0vrKhoE6SDkCbESnRWVRw0hAVaexwnnVoi
    V5JmqdoMLWq0ggdMTw5prlsSr1xu2VmxIhxGYOiVKX2Z1IGboriz7+59JtMaas7U
    m+hiVgho8jS5r+cXr47pNWxL+b8Qp0HcpENAvoDBUZb0lGL9WAAt6UsCAwEAAaMn
    MCUwDgYDVR0PAQH/BAQDAgWgMBMGA1UdJQQMMAoGCCsGAQUFBwMCMA0GCSqGSIb3
    DQEBCwUAA4IBAQCgSv7fW4gfJsg+CQPPRtFnAGO+VNDxXuN+WrHGB1gWiiCFkUJ8
    TzIGPlKl0Zq8bJqNi8j7uUhGBfNTWmrJc4bVzwELtqkP1K0xd0EBTN2BkNiWc205
    EWKOsvSsof7WU1hC57UO6m/Hadst9yQBRdfROvVbPBOYmYJw2upQ05sahlrcH0ZJ
    bKCNRSIGDl47UyzhXovN/HQaTSSVx7/LCzeesro5Os4PwFUh76jjihYWuAZiapQB
    6fUquOtPRUYQt4xK9jsy21T4vk/ubEGhUwjgD+ZzB8+TE2XHY26xNd7JlpaA+xXq
    zTaiij/nhVP0FDPcquEAEqTDS+uYjwRVvpmr
    -----END CERTIFICATE-----
  kubelet-client.key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEowIBAAKCAQEAuqynqAykP7uAXMl9RGurIQzLElMxuumJgf0QzJhBWdmAkYqi
    BigvJg75Ua2GHCr+HXMzRag70uDiCNYMA4ITy4Z5f54jd24/pikGRTH7LmNUaCan
    H77zvZXHV2hJ211CCDoiDCZDOpLCFQXKbzVgi9e5G8OEP+RXjBQL+ou11ZsjRJEG
    yLSWWPAg+P8j7S+sqGgTpIOQJsRKdFZVHDSEBVp7HCedWiJXkmap2gwtarSCB0xP
    DmmuWxKvXG7ZWbEiHEZg6JUpfZnUgZuiuLPv7n0m0xpqztSb6GJWCGjyNLmv5xev
    juk1bEv5vxCnQdykQ0C+gMFRlvSUYv1YAC3pSwIDAQABAoIBACSEKbfB4U9mSlHc
    SFjeBvfMHN1U0OGTVYbMDkE3d3EwDuppiBBURATZ4QONQjK4ZkU0h88Ufb9epli8
    JlV5WI3znEjOknmGY4UJeWSHxm7ol1ZYWVDodZ2ccwYyLGBw+b3KQWbHBVer5bNf
    Ep52fpBcfqVjtbcZ39ZTBZTZR5SlEjXS3YI7q6m1+P48+jyVqo4chhgo+fINa8+d
    goBHQBPvDEZRkew+SMIcjWNBCkucw42PtAtCHS79pblJ0r+7apLBp/tFzT7NYna9
    jSKOUx8XGjzGNIUu64vUBkj8RbtRrWKbZUTaLwk/sniwzykA+8hXI0eJdYzDr0gD
    1PZ/oiECgYEAwbE7HnmQusxg5NH5UP0+c6qdlitHS68HvlVlmYp4lSTuS9hMdoPJ
    sn3a/Peuh0alLIiGCoUPyVec+/Be0bSSDeDGXXgov7eNohV8GiZYDJOIKreNWCHX
    e0GRXYKztBDIADvu7erAQYdClW6sc5TY6iSbscFpYS+vZx3NVDzwpD0CgYEA9rl+
    k8d9ClQOGkf4y3pJvdQI3lk5WZL8ke5ZkQo7FlnuIy027GmNV6xct/2ieHBwepc7
    LEZz2F8FJHd+aqjAnto1HZ6it8y0Y4sI2fZfm9a4F+gaRDXn8jBzJ7VXp5V1Yuch
    QCiangpIqJl92EMtU4iUrtc2IVKO0iN/eJLStCcCgYB1ywLZFbUe5QxIHCozRs+k
    KC6OFOPW8ysSZXzUU5HhogQJvBFEQgF3u3JiRX6uZhgtbRmXbDSdjdq6nQQNJHNu
    XTRFw72EWmyYFdjTTl5dx5sX32jmIC6bltSAuevvpgT7n3c+2XTyZP/pQNU/tVX1
    jy3gfG9J22Ygn88vW6A9QQKBgQC2qkUNkk+AOxUp3glUVNiNw5NBU5vDNrDqNiZ3
    3LQ8ax6FSq90Pv2XYJRQ4GbOdqjACoGT2SFhm5AKHLIqs3/Q3Esg/9cG73bKkCBg
    hyjoDwPDJ2NzBtoQFFDdoEQiXeRH8klK4AUBZym+Mc3bNHk1dFRoUgvQhfgZmpCA
    q2t2VwKBgAFg9ivier/Sx9wAt0nL6FJVQHAzdgtP8m4nR9y6ZsbZ/UjEOpIwVhHn
    +A5SR7n5TDdxyjkhvS0jdxvLsrHBhpddz6cd4mXbwvfIQCOyOfORmK92KSC17bS1
    tJD22cnNFmVnTCQhb+GUJDr9yO1SD379GTwo7FpyLPxeCp+92V8e
    -----END RSA PRIVATE KEY-----